### ISSUE TITLE
Renaming packages

### ISSUE THREAD

**Issue by milankl** [AtilaSaraiva/SequentialZfpCompression.jl#2]
Oh no, now you lost the link to the previous package! Just FYI if you rename a repo on github then a permanent forwarding from the old link to the new is created. I believe that link is on the http level so you don't even interfere with git clones. But now both repo names existed independently so I am not sure you can link them again. So best practice is actually to rename a package in the danger zone which is surprisingly smooth.

**Comment by AtilaSaraiva** [comment]
I tested the link thing but it didnt work sadly, hence this solution. But I linked the new repo in the old repo. Now it is kinda done so I`m gonna roll with it haha.

**Comment by AtilaSaraiva** [comment]
Oh seems like people create a fork with the old name of the repo to redirect people.
